#Configure your options here
#MPI_ROOT = /usr/local
LEVEL_DB_ROOT			= /users/hng/leveldb-1.12.0
ROCKS_DB_ROOT			= /users/hng/rocksdb-2.6.fb
MPI_TO_OPENSHMEM_ROOT	= /users/gingery/mpi_to_openshmem/src/
OPENSHMEM_ROOT			= /users/gingery/openshmem-1.0e_IBV/
GASNET_ROOT				= /users/gingery/GASNet-1.20.2_standard/

LEVELDB = 1
ROCKSDB = 0

#CC		= mpicc -g -O0 -Wall
CC		= oshcc -g -O0 -Wall

#You shouldn't have to modify anything below
CLIBS	= -L/usr/lib64 -L${LEVEL_DB_ROOT} -L${MPI_TO_OPENSHMEM_ROOT}/src -L${OPENSHMEM_ROOT}/lib -L${GASNET_ROOT}/lib/gasnet-ibv-par -libverbs
CINC	=  -I${LEVEL_DB_ROOT}/include -I${MPI_TO_OPENSHMEM__ROOT}/src  -I${OPENSHMEM_ROOT}/include -I${GASNET_ROOT}/include  -IMlog/ -Iuthash


#CLIBS = -L$(MPI_ROOT)/lib
#CINC = -I$(MPI_ROOT)/include -IMlog/ -Iuthash
#CFLAGS = -lmpich -lmdhim -lm -lpthread -lstdc++

CFLAGS = -lmdhim -lm -lpthread -lstdc++

ifeq ($(LEVELDB),1)
  CLIBS  += -L$(LEVEL_DB_ROOT) -DLEVELDB_SUPPORT
  CINC   += -I$(LEVEL_DB_ROOT)/include
  CFLAGS += $(LEVEL_DB_ROOT)/libleveldb.a
endif

ifeq ($(ROCKSDB),1)
  CLIBS  += -L$(ROCKS_DB_ROOT) -DROCKSDB_SUPPORT
  CINC   += -I$(ROCKS_DB_ROOT)/include
  CFLAGS += -lsnappy -lbz2 $(ROCKS_DB_ROOT)/librocksdb.a
endif

